; COMMON options
; Each "[env:***]" extends this "[env]" by default
[env]
platform = espressif8266
framework = arduino
; build_flags = 
; 	-D WIFI_SSID="\"${sysenv.WIFI_SSID}\""
; 	-D WIFI_PASSWORD="\"${sysenv.WIFI_PASSWORD}\""
; 	-D MQTT_SERVER="\"${sysenv.MQTT_SERVER}\""
; 	-D MQTT_USERNAME="\"${sysenv.MQTT_USERNAME}\""
; 	-D MQTT_PASSWORD="\"${sysenv.MQTT_PASSWORD}\""

[env:nisse]
board = d1_mini
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
upload_protocol = espota
upload_port = nisse.local
upload_flags = 
	--auth=nisse
build_flags =
	${env.build_flags}
	-D BOARD_ID='"nisse"'
	-D SERVO_ENABLED
	-D SERVO_PIN=5

[env:toiletgpio]
board=nodemcuv2
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
	eegee-tokyo/DHT sensor library for ESPx@^1.18.0
upload_protocol = espota
upload_port = toiletgpio.local
upload_flags = 
	--auth=toiletgpio
build_flags = 
	${env.build_flags}
	-D BOARD_ID='"toiletgpio"'
	-D DHT_ENABLED
	-D DHT_PIN=16
	-D PIR_ENABLED
	-D PIR_PIN=4

[env:toslinkirda]
board = d1_mini
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
	z3t0/IRremote@^3.6.1
upload_protocol = espota
upload_port = toslinkirda.local
upload_flags = 
	--auth=toslinkirda
build_flags = 
	${env.build_flags}
	-D BOARD_ID='"toslinkirda"'
	-D IRDA_ENABLED
	-D IRDA_SEND_PIN=5

[env:desk]
board = nodemcuv2
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
upload_protocol = espota
upload_port = desk.local
upload_flags = 
	--auth=desk
build_flags = 
	${env.build_flags}
	-D BOARD_ID='"desk"'
	-D DESK_ENABLED=1
	-D DESK_UP_PIN=4
	-D DESK_DOWN_PIN=5
	-D DESK_HC_ECHO_PIN=15
	-D DESK_HC_TRIG_PIN=2

[env:plant-ciuffo]
board = d1_mini
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
upload_protocol = espota
upload_port = plant-ciuffo.local
upload_flags = 
	--auth=plant-ciuffo
build_flags = 
	${env.build_flags}
	-D BOARD_ID='"plant-ciuffo"'
	-D SOIL_MOISTURE_ENABLED=1