; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nisse]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
upload_protocol = espota
upload_port = nisse.local
upload_flags = 
	--auth=nisse
build_flags = 
	-D BOARD_ID='"nisse"'
	-D SERVO_ENABLED
	-D SERVO_PIN=5

[env:toiletgpio]
platform = espressif8266
board=nodemcuv2
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
	eegee-tokyo/DHT sensor library for ESPx@^1.18.0
upload_protocol = espota
upload_port = toiletgpio.local
upload_flags = 
	--auth=toiletgpio
build_flags = 
	-D BOARD_ID='"toiletgpio"'
	-D DHT_ENABLED
	-D DHT_PIN=16
	-D PIR_ENABLED
	-D PIR_PIN=4

[env:toslinkirda]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
	z3t0/IRremote@^3.6.1
upload_protocol = espota
upload_port = toslinkirda.local
upload_flags = 
	--auth=toslinkirda
build_flags = 
	-D BOARD_ID='"toslinkirda"'
	-D IRDA_ENABLED
	-D IRDA_SEND_PIN=16

[env:desk]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
upload_protocol = espota
upload_port = desk.local
upload_flags = 
	--auth=desk
build_flags = 
	-D BOARD_ID='"desk"'
	-D UP_DOWN_ENABLED=1
	-D UP_PIN=5
	-D DOWN_PIN=4

[env:plant-ciuffo]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
	knolleary/PubSubClient@^2.8.0
	https://github.com/tzapu/WiFiManager
; upload_protocol = espota
; upload_port = desk.local
; upload_flags = 
; 	--auth=desk
build_flags = 
	-D MQTT_SERVER='"192.168.0.240"'
	-D MQTT_USERNAME='"kopiro"'
	-D MQTT_PASSWORD='"kopiro"'
	-D WIFI_SSID='"OttoHome2"'
	-D WIFI_PASSWORD='"rispondiunoodue"'
	-D BOARD_ID='"plant-ciuffo"'
	-D SOIL_MOISTURE_ENABLED
	-D DEEP_SLEEP_MAX